package com.yzx.rest.util;

public class SqlCode {
	/*master*/  
	public final static String QUERY_ACCOUNT_BY_ID="select t.sid,t.token,date_format(t.create_date,'%Y-%m-%d %H:%i:%s') as create_date,date_format(t.update_date,'%Y-%m-%d %H:%i:%s') as update_date,t.realname,t.user_type,t.`status`,t.email,t.mobile,t.random_nbr,t.username,is_proxy,intern_rate from tb_ucpaas_user t where sid=? and status!='6'";
	public final static String QUERY_APP_BY_ID="select app_sid,sid,app_name,date_format(create_date,'%Y-%m-%d %H:%i:%s') as create_date,industry,sms_msg_nbr,`status`,app_type,is_show_nbr,brand,ck_num,hidden_numGroupid,route_area from tb_ucpaas_application where app_sid=?  and `status`!='3'";
	public final static String QUERY_CLIENT_BY_NAME="select client_sid,sid,client_token,friendly_name,date_format(create_date,'%Y-%m-%d %H:%i:%s') as create_date,client_number,client_pwd,status,app_sid,mobile,cast(charge_type-1 as signed integer) as client_type,charge_type,is_call_fr from tb_ucpaas_client where status in('1','2') and client_number=? and sid=?";
	public final static String QUERY_CLIENT_BY_MOBILE="select client_sid,sid,client_token,friendly_name,date_format(create_date,'%Y-%m-%d %H:%i:%s') as create_date,client_number,client_pwd,status,app_sid,mobile,CONCAT(charge_type)-1 as client_type,charge_type,is_call_fr from tb_ucpaas_client where  app_sid=? and status in('1','2')  and mobile=?";
	public final static String QUERY_WHITE_LIST_BY_APPID="select white_address from tb_srv_white_list where app_sid=?";
	public final static String CHECK_CLIENT_APP="select count(1) from tb_ucpaas_client where client_number=? and app_sid=?";
	public final static String QUERY_WHITE_LIST="select mobile from tb_ucpaas_test_whitelist where sid=? and `status`=1";
	public final static String QUERY_BALANCE="select b.balance,b.enable_flag from tb_bill_acct_balance b where sid=?";
	
	public final static String NEXT_VALUE_NUM="select cur_num from tb_sequence LIMIT 1";
	public final static String UPDATE_NUM="update tb_sequence set cur_num=? where 2>1"; 
	public final static String QUERY_BALANCE_BY_SID="select balance from tb_bill_acct_balance where sid=?";
	public final static String QUERY_BALANCE_BY_SID2="select balance,enable_flag,credit_balance from tb_bill_acct_balance where sid=?";
	public final static String QUERY_CLIENT_BALANCE_BY_NBR="select balance from tb_bill_client_balance where client_number=? and enable_flag='1';";
	public final static String UPDATE_CLIENT_STATUS="update tb_ucpaas_client set `status`='0',mobile='',update_date=now() where client_number=?";
	public final static String QUERY_CLIENTS="select a.client_sid,a.client_token,date_format(a.create_date,'%Y-%m-%d %H:%i:%s') as create_date,a.client_number,a.client_pwd,a.friendly_name,CONCAT(a.charge_type)-1 as client_type,a.mobile,b.balance/1000000 as balance from tb_ucpaas_client a,tb_bill_client_balance b where a.client_number=b.client_number and a.status in('1','2') and a.app_sid=? LIMIT ?,?";
	public final static String UPDATE_BALANCE="update tb_bill_acct_balance set balance=balance-? where sid=?";
	public final static String QUERY_FEE_BY_ID="select a.fee from tb_bill_fee_item a,tb_bill_fee_item_rel b,tb_bill_acct_package_rel c where a.fee_id=b.fee_id and b.package_id=c.package_id and c.sid=? and a.fee_id like ?";
	public final static String QUERY_CLIENT_BAND_MOBILE="select count(1) from tb_ucpaas_client where app_sid=? and mobile=?";
	public final static String QUERY_SAFE_PHOE="select count(1) from tb_ucpaas_safe_phone_list where phone=?";
	public final static String QUERY_USER_BY_LOGIN="select a.sid,a.token,a.`status`,b.app_sid from tb_ucpaas_user a,tb_ucpaas_application b where a.sid=b.sid and b.app_type='0' and a.`password`=? and (a.email=? or a.mobile=?) ORDER BY b.app_sid";
	public final static String QUERY_CLIENT_BY_APPSID_FOR="select client_number,client_pwd,mobile from tb_ucpaas_client where app_sid=? and client_type='0' and status='1'";
	public final static String BAND_CLIENT_MOBILE="update tb_ucpaas_client set mobile=?,update_date=now() where client_number=?";
	public final static String QUERY_CLIENT_BY_FRIENDLYNAME="select client_sid,sid,client_token,friendly_name,date_format(create_date,'%Y-%m-%d %H:%i:%s') as create_date,client_number,client_pwd,status,app_sid,mobile,CONCAT(charge_type)-1 as client_type,charge_type from tb_ucpaas_client where friendly_name=? AND app_sid=? and status in('1','2')";
	public final static String UPDATE_CLIENT_BALANCE="UPDATE tb_bill_client_balance set enable_flag='0',update_date=now() where client_number=?";
	public final static String DEL_MOBILE="DELETE FROM tb_ucpaas_client_pool where mobile=(SELECT mobile from tb_ucpaas_client WHERE client_number=?) and appid=?";
	public final static String QUERY_CLIENT_COUNT2="select count(1) from tb_ucpaas_client where app_sid=?";
	public final static String UPDATE_CLIENT_FEE="INSERT INTO tb_event_fee_[DATE](sid,app_sid,client_count,fee,one_fee,event_id,fee_date,create_date,client_number,fee_type)VALUES(?,?,1,?,?,?,now(),now(),?,?)";
	public final static String UPDATE_CLIENT_VERIFY="update tb_ucpaas_client set is_verify=?,update_date=now() where client_number=?";
	public final static String UPDATE_CLIENT_PWD="update tb_ucpaas_client set client_pwd=? where client_number=? and app_sid=?";
	public final static String ROAM_OPEN="UPDATE tb_ucpaas_client SET is_call_fr=?,update_date=NOW() WHERE client_number=?";
	public final static String MONITOR="select now()";
//	public final static String QUERY_SQL_CODE="select sql_code,sql_desc from tb_srv_sql ";
//	public final static String ADD_CLIENT="INSERT into tb_ucpaas_client (client_sid,app_sid,friendly_name,client_number,client_pwd,client_token,status,create_date,update_date,sid,charge,charge_type,mobile,client_type) VALUES(?,?,?,?,?,?,?,now(),now(),?,?,?,?,?)";
//	public final static String QUERY_CLIENT_BY_APP_NAME="select count(1) from tb_ucpaas_client where status='1' and app_sid=? and friendly_name=?";
//	public final static String QUERY_FILE_BY_LOCALURL="select token,remote_path from statistics.tb_srv_file_[DATE] where local_path=?";
//	public final static String QUERY_PARAMS_BY_TYPE="select param_value from tb_ucpaas_params where param_type=?";
//	public final static String ADD_MSG_LOG="insert into ucpaas_statistics.tb_sms_log_[DATE](sms_id,from_number,to_number,start_time,content,sid,status,app_sid,len_type,msg_type,template_id,fee,msg_index,template_param,rest_ip,meet_id,interface_ip)VALUES(?,?,?,now(),?,?,?,?,?,?,?,?,?,?,?,?,?)";
//	public final static String ADD_MSG_LOG2="insert into ucpaas_statistics.tb_sms_log_[DATE](sms_id,start_time,status,fee,msg_index)VALUES(?,now(),?,?,?)";
//	public final static String ADD_MSG_LOG3="insert into ucpaas_statistics.tb_sms_log_[DATE](sms_id,from_number,to_number,start_time,content,sid,status,app_sid,len_type,msg_type,template_id,fee,msg_index,template_param) select sms_id,from_number,to_number,now(),content,sid,?,app_sid,len_type,msg_type,template_id,?,?,template_param from ucpaas_statistics.tb_sms_log_[DATE] where sms_id=? and msg_index=1 LIMIT 1";
//	public final static String UPDATE_APP_BALANCE="update tb_ucpaas_app_balance set balance=balance-? where app_sid=?";
//	public final static String QUERY_TEMPLATE_MSG="select content,`status`,sign,`type`,app_sid,name  from tb_srv_sms_template where template_id=?";
//	public final static String QUERY_TEMPLATE_MSG2="select content,`status`,sign,`type` from tb_srv_sms_template where template_id=? and (app_sid=? or 1=1) and `status`=2";
//	public final static String UPDATE_TB_SMS_LOG_1="update ucpaas_statistics.tb_sms_log_[DATE] set status=?,fee=? where sms_id=? and msg_index=?";
//	public final static String ADD_VERIFY_CODE="insert into ucpaas_statistics.tb_verify_code_log_[DATE](verify_code,to_number,display_num,sid,app_sid,fee,call_id,status,create_date,vtype,rest_ip)values(?,?,?,?,?,?,?,?,now(),?,?)";
//	public final static String UPDATE_VERIFY_CODE="update ucpaas_statistics.tb_verify_code_log_[DATE] set fee=?,status=?,Areqtime=?,Aringtime=?,Aconntime=?,Aendtime=?,cb_ip=?,delay=?,endreason=?,cbdisplay=? where call_id=?";
//	public final static String QUERY_FEE_BY_ID2="select a.fee from tb_bill_fee_item a,tb_bill_fee_item_rel b,tb_bill_acct_package_rel c where a.fee_id=b.fee_id and b.package_id=c.package_id and c.sid=? and a.fee_id like ? and a.is_show_nbr=?";
//	public final static String QUERY_TEMP_MSG_SEND="select count(1) from ucpaas_statistics.tb_sms_log_[DATE] where template_id=? and to_number=? and template_param=?  and app_sid=?  and status='1'";
//	public final static String UPDATE_CLIENT_DISPLAY="update tb_ucpaas_client set is_show_nbr=?,update_date=now() where client_number=? and app_sid=?";
//	public final static String ADD_TEST_NUMBER="insert INTO tb_ucpaas_test_number(sid,test_id,clientnum)VALUES(?,?,?)";
//	public final static String QUERY_TEST_NUMBER="select count(1) from tb_ucpaas_test_number where clientnum=?";
//	public final static String UPDATE_TEST_NUMBER="update tb_ucpaas_test_number set test_id=? where clientnum=?";
//	public final static String QUERY_SHOW_NBR="select nbr as num from tb_ucpaas_application_shownbrs where app_sid=? and `status`='3' and nbr=?";
//	public final static String ADD_MID_LOG="insert into ucpaas_statistics.tb_mid_log_[DATE](sid,app_sid,fee,create_date)values(?,?,?,now())";
//	public final static String PROC_ADDCLIENT="{call p_reg_app_clientid(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)}";
//	public final static String PROC_ADDCLIENT_NEW="{call p_reg_app_clientid_new(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)}";
//	public final static String PROC_ADDCLIENT_UIN="{call p_reg_app_clientid_uin(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)}";
//	public final static String QUERY_APP_BALANCE="select balance from tb_ucpaas_app_balance where app_sid=?";
//	public final static String QUERY_SMS_COUNT="SELECT count(1) FROM ucpaas_statistics.tb_sms_log_[DATE] WHERE app_sid=? AND to_number=?";
//	public final static String QUERY_VERIFY_COUNT="SELECT COUNT(1) FROM ucpaas_statistics.tb_verify_code_log_[DATE] WHERE app_sid=? AND to_number=?";
//	public final static String ADD_NOTIFY="insert into tb_notify_call_file(sid,app_sid,audit_status,upload_status,create_date,update_date,content,`to`,toServNum,`type`,playTimes,send_status,is_contract,call_id,call_time)values(?,?,1,1,now(),now(),?,?,?,0,?,1,?,?,?)";
//	public final static String QUERY_CALL_ADDRESS="select call_address from tb_srv_callback where app_sid=? and call_type=4";
//	public final static String QUERY_SHOW_NUMBER="select nbr from tb_ucpaas_application_shownbrs where app_sid=? and `status`='1'";
//	public final static String ADD_NOTIFY_LOG="insert into ucpaas_statistics.tb_notify_log_[DATE](`to`,`type`,sid,app_sid,fee,call_time,call_id,`status`,playTimes,display_num,content,create_date,update_date,send_time,is_show,rest_ip)values(?,?,?,?,0,0,?,0,?,?,?,now(),now(),?,?,?)";
//	public final static String UPDATE_NOTIFY="update ucpaas_statistics.tb_notify_log_[DATE] set fee=?,call_time=?,`status`=?,update_date=now(),Areqtime=?,Aringtime=?,Aconntime=?,Aendtime=?,cb_ip=?,delay=?,endreason=?,cbdisplay=? where call_id=?";
//	public final static String QUERY_FILENAME="select file_path,file_name from tb_notify_call_file where id in([VOICEID]) and audit_status in(2,5) and upload_status=3 and app_sid=?";
//	public final static String QUERY_USER_C="select is_contract from tb_ucpaas_user where sid=?";
//	public final static String ADD_TEMPLATE="INSERT INTO tb_srv_sms_template(app_sid,`name`,content,`status`,create_date,update_date)VALUES(?,?,?,'1',now(),now())";
//	public final static String QUERY_TEMPLATE_ID="select template_id from tb_srv_sms_template where app_sid=? and `name`=? and content=? ORDER BY template_id DESC limit 1";
//	public final static String QUERY_SERVICE_BALANCE="SELECT  s.id,s.meet_id,s.balance,t.fee  FROM  tb_service_balance s,(SELECT  a.fee FROM  tb_bill_fee_item a,tb_bill_fee_item_rel b,tb_bill_acct_package_rel c  WHERE  a.fee_id = b.fee_id  AND b.package_id = c.package_id  AND c.sid = ?  AND a.fee_id LIKE CONCAT(?, '%')) t  WHERE  s.sid = ?  AND s.`status` = 1  AND s.eff_date <= NOW()  AND s.exp_date > NOW()  AND s.event_id = ?  AND s.balance >= t.fee  ORDER BY  s.exp_date  LIMIT 1";
//	public final static String UPDATE_SERVICE_BALANCE="update tb_service_balance set balance=balance-? where sid=? and event_id=?";
//	public final static String UPDATE_SERVICE_BALANCE_BY_ID="update tb_service_balance set balance=balance-? where id=?";
//	public final static String ADD_APP="INSERT into tb_ucpaas_application(app_sid,sid,app_name,app_kind,is_show_nbr,industry,create_date,call_fr)VALUES(?,?,?,?,?,?,now(),?)";
//	public final static String UPDATE_TEMPLATE="update tb_srv_sms_template set content=?,update_date=now() where template_id=? and `status`!=4 and app_sid=?";
//	public final static String QUERY_APP_BY_NAME="select count(1) from tb_ucpaas_application where sid=? and app_name=? and `status`!='3'";
//	public final static String QUERY_CALL_ADDRESS2="select call_address from tb_srv_callback where app_sid=? and call_type=?";
//	public final static String QUERY_ROAM_EREA="SELECT area_id from t_sms_phone_section where phone_section=?";
//	public final static String QUERY_ROAM_PHONE="select forwardnumber from (select forwardnumber from(SELECT forwardnumber from t_forward_number_list where areaid=? order by rand()) AS t1 UNION SELECT forwardnumber from t_forward_number_list where areaid=0) as t LIMIT 1;";
//	public final static String QUERY_TRADE_PHONE="select forwardnumber from (select forwardnumber from(SELECT forwardnumber from t_trade_number_list where areaid=? and `status`=0 order by rand()) AS t1 UNION SELECT forwardnumber from t_trade_number_list where areaid=0) as t LIMIT 1";
//	public final static String UPDATE_TRADE_PHONE="UPDATE t_trade_number_list SET `STATUS`=? WHERE groupid=? and forwardnumber=?";
//	public final static String ADD_ROAM="INSERT INTO tb_ucpaas_roam(client_number,exp_days,create_date,update_date,call_mode,phone,sid,app_sid,forward_phone)VALUES(?,?,NOW(),NOW(),?,?,?,?,?)";
//	public final static String UPDATE_ROAM="UPDATE tb_ucpaas_roam SET exp_days=exp_days+?,update_date=NOW(),call_mode=? WHERE client_number=? and `status`=1";
//	public final static String UPDATE_ROAM2="UPDATE tb_ucpaas_roam SET exp_days=exp_days+?,update_date=NOW(),call_mode=?,forward_phone=? WHERE client_number=? and `status`=1";
//	public final static String CLOSE_ROAM="UPDATE tb_ucpaas_roam SET `status`=0,update_date=now(),exp_date=now() where client_number=? and `status`=1";
//	public final static String QUERY_ROAM_DAYS="select date_format(create_date,'%Y%m%d%H') as create_date,exp_days from tb_ucpaas_roam where client_number=? and `status`=1";
//	public final static String QUERY_ROAM_COUNT="select count(1) from tb_ucpaas_roam where client_number=? and `status`=1";
//	public final static String UPDATE_CLIENT_BALANCE2="UPDATE tb_bill_client_balance set balance=balance-?,update_date=now() where client_number=?";
//	public final static String QUERY_ALL_KEY_WORDS="select word from tb_ucpaas_filter_keyword";
//	public final static String QUERY_VOICE_FILE_NAME="select file_name from tb_ucpaas_call_ring where `id`=? and `type`=2 and app_sid=? and audit_status=2";
//	public final static String QUERY_MISS_CALL="select callid,callerid,calleeid,calltime,errcode,callerphone,calleephone from t_misscallrecord_list_[DATE] where calleeid=?";
//	public final static String QUERY_VOICE_FILE_NAME2="select file_name from tb_ucpaas_call_ring where app_sid=? and `type`=2 and audit_status=2 limit 1";
//	public final static String ADD_TRADE_ORDER="INSERT INTO tb_ucpaas_trade_order(order_id,sid,app_sid,calla,callb,ucpaas_number,create_date,maxduration,group_id)VALUES(?,?,?,?,?,?,now(),?,?)";
//	public final static String QUERY_TRADE="SELECT group_id,ucpaas_number from tb_ucpaas_trade_order where order_id=? and app_sid=?  ";
//	public final static String ADD_TRADE_HIS="INSERT INTO tb_ucpaas_trade_order_his(order_id,sid,app_sid,calla,callb,ucpaas_number,create_date,end_date,maxduration,group_id) SELECT order_id,sid,app_sid,calla,callb,ucpaas_number,create_date,NOW(),maxduration,group_id FROM tb_ucpaas_trade_order where order_id=? and app_sid=?";
//	public final static String DEL_TRADE="DELETE FROM tb_ucpaas_trade_order where order_id=? and app_sid=?  ";
//	public final static String QUERY_TRADE_ORDER="SELECT order_id,sid,app_sid,calla,callb,ucpaas_number,date_format(create_date,'%Y-%m-%d %H:%i:%s') create_date,date_format(end_date,'%Y-%m-%d %H:%i:%s') end_date,maxduration FROM tb_ucpaas_trade_order_his where order_id=? and app_sid=? UNION ALL SELECT order_id,sid,app_sid,calla,callb,ucpaas_number,date_format(create_date,'%Y-%m-%d %H:%i:%s') create_date,date_format(end_date,'%Y-%m-%d %H:%i:%s') end_date,maxduration FROM tb_ucpaas_trade_order where order_id=? and app_sid=?";
//	public final static String QUERY_LINE_GROUP="select a.forwardnumber,c.group_id FROM t_trade_number_list a,(select max(con),group_id FROM (select group_id,SUM(max_con-cur_con) con FROM tb_ucpaas_line_group where area_id=? GROUP BY group_id HAVING con>1) b ) c where a.groupid=c.group_id AND a.`status`=0 [COND] order by rand() limit 1";
//	public final static String QUERY_TRADE_NUM="SELECT ucpaas_number from tb_ucpaas_trade_order where calla=? or callb=?";
//	public final static String QUERY_LINE_GROUP_RANDOM="SELECT a.forwardnumber,c.group_id FROM t_trade_number_list a,(select max(con),group_id FROM (SELECT group_id,SUM(max_con-cur_con) con FROM tb_ucpaas_line_group GROUP BY group_id HAVING con>1) b ) c where a.groupid = c.group_id AND a.`status` = 0 [COND] ORDER BY rand() LIMIT 1";
//	public final static String QUERY_TEMPLATE_MSG3="select a.content,a.`status`,a.sign,a.`type` from tb_srv_sms_template a,tb_ucpaas_application b WHERE a.app_sid=b.app_sid AND a.template_id=? and b.sid=? and a.`status`=2";
//	public final static String QUERY_APP_CURCONC="select sum(concurrency) as curconc from tb_ucpaas_concurrency where app_sid=? and date_format(create_date,'%Y%m%d%H%i')=? and if_type=?";
//	public final static String QUERY_INDIV_VERIFYCODE="SELECT v.`mode`,v.templateid,v.speed from tb_verifycode v WHERE v.appid = ?";
	
}
